### ISSUE TITLE
Timecodes for "DE Zoomcamp 2.3.1 - Setup Airflow Environment with Docker-Compose"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/data-engineering-zoomcamp#167]
Youtube video: https://www.youtube.com/watch?v=lqDMzReAtrw

**Comment by boisalai** [comment]
Hi, 

I found something

I followed the steps and updated the version numbers (Airflow 2.5.0 and Google Cloud SDK/CLI 412.0.0) in the Dockerfile.

But at 10:00, with `docker-compose build`, I get this error :
```
> [airflow-airflow-init 4/8] RUN pip install --no-cache-dir -r requirements.txt:
#0 0.187 
#0 0.187 You are running pip as root. Please use 'airflow' user to run pip!
#0 0.187 
#0 0.187 See: https://airflow.apache.org/docs/docker-stack/build.html#adding-a-new-pypi-package
#0 0.187 
------
failed to solve: executor failed running [/bin/bash -o pipefail -o errexit 
-o nounset -o nolog -c pip install --no-cache-dir -r requirements.txt]: exit code: 1
```
I don't know it's related, but this post (https://stackoverflow.com/a/72296552) says that this bug was introduced in 2.3.0.

If I keep the initial versions 2.2.3 for Airflow and 322.0.0 for Google Cloud SDK/CLI in Dockerfile, everything works fine.

Alain

**Comment by dimzachar** [comment]
0:00:03 - Airflow workshop: Docker setup, injection pipeline
0:02:54 - Configure Docker settings, download Airflow image
0:05:57 - Dags, logs, plugins, docker, requirements, examples
0:09:19 - Confusing setup, build image, initialize Docker
0:12:36 - Initialize airflow container with default credentials

**Comment by amitfrancis** [comment]
Updated timecodes! Thanks :)
