### ISSUE TITLE
dlt workshop q4 issue

### ISSUE THREAD

**Issue by aturevich** [DataTalksClub/data-engineering-zoomcamp#483]
Hello there, there is high chance that there is mistake in q4 for dlt workshop

Here are my points. In the end we have to end with tables, excluding blue lines, as they come from first generator and should be updated with values from second generator
![image](https://github.com/DataTalksClub/data-engineering-zoomcamp/assets/150670914/14220cf4-0a56-48b0-b9bd-7a25854774ae)

Tried couples of approaches in code, but ended with same answer. If we try to add up age values manually, than no answer will match our result.

![image](https://github.com/DataTalksClub/data-engineering-zoomcamp/assets/150670914/450f2977-4923-488d-a80c-18c55f3d02d2)

Probably form needs update

**Comment by alexeygrigorev** [comment]
@adrianbr can you please take a look?

**Comment by askeladden31** [comment]
The problem was described in https://github.com/DataTalksClub/data-engineering-zoomcamp/pull/461

The code used to procure the solutions erroneously used different table names for merging, which caused the resulting sum to be 213 (age values from second generator only), which apparently is what is used by the form now.

**Comment by aturevich** [comment]
Answers were fixed. Closing.
